plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "com.arcuscomputing.dictionary.reloaded"

    defaultConfig {
        applicationId "com.arcuscomputing.dictionary.reloaded"
        compileSdk(36)
        minSdk 24
        targetSdk 36
        versionCode 301
        versionName "3.0.1"
    }

    signingConfigs {
        release {
            storeFile file("./release.keystore")
            storePassword ""
            keyAlias ""
            keyPassword ""
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources = true
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

    lint {
        abortOnError true
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.annotation
    implementation libs.google.material
    implementation libs.timber
    implementation libs.okio

    testImplementation libs.junit
    testImplementation libs.mockito.kotlin
    testImplementation libs.robolectric
    testImplementation libs.kotlin.coroutines.test
    testImplementation libs.androidx.test.core
}
