plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    compileSdk 35
    namespace 'com.arcuscomputing.dictionarypro.ads'

    defaultConfig {
        applicationId "com.arcuscomputing.dictionarypro.ads"
        minSdk 24
        targetSdk 35
        versionCode 301
        versionName "3.0.1"
    }

    signingConfigs {
        release {
            storeFile file("./release.keystore")
            storePassword ""
            keyAlias ""
            keyPassword ""
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.annotation
    implementation libs.google.material
    implementation libs.timber
    implementation libs.okio

    testImplementation libs.junit
    testImplementation libs.mockito.kotlin
    testImplementation libs.robolectric
    testImplementation libs.kotlin.coroutines.test
    testImplementation libs.androidx.test.core
}
